version: '3'
networks:
  alunos-net:
services:
  personas-db:
    container_name: alunos-db
    image: postgres:14-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=alunos
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=develop
    networks:
      - alunos-net
    # volumes:
    # - ./migration/docker-database-initial.sql:/docker-entrypoint-initdb.d/docker-database-initial.sql